spring:
  application:
    name: hibernate_1
  datasource:
    url: jdbc:mariadb://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false